import type { AppData } from './storage';

export const seedData: AppData = {
  orders: [
    {
      id: 'ord_1',
      reference: 'XM-482931',
      status: 'delivered',
      statusTimeline: [
        { status: 'pending', label: 'Booking Received', timestamp: '2026-06-01T09:00:00Z', note: 'Customer booked online' },
        { status: 'confirmed', label: 'Confirmed', timestamp: '2026-06-01T10:30:00Z' },
        { status: 'scheduled', label: 'Scheduled', timestamp: '2026-06-02T08:00:00Z', note: 'Crew A assigned' },
        { status: 'dispatched', label: 'Dispatched', timestamp: '2026-06-03T07:45:00Z' },
        { status: 'in_transit', label: 'In Transit', timestamp: '2026-06-03T08:15:00Z' },
        { status: 'delivered', label: 'Delivered', timestamp: '2026-06-03T09:30:00Z', note: 'Photos uploaded by Mike' },
      ],
      serviceType: ['delivery'],
      items: [
        { id: 'itm_1', category: 'sofa', name: '3-Seat Sofa', quantity: 1, price: 120, action: 'deliver' },
        { id: 'itm_2', category: 'bed', name: 'Queen Bed Frame', quantity: 1, price: 110, action: 'deliver' },
      ],
      pricing: { subtotal: 230, discount: 0, tax: 19.55, total: 249.55 },
      affiliateCode: 'MIKE10',
      photos: [],
      deliveryPhotos: [
        { id: 'dp_1', url: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=600&h=400&fit=crop', uploadedAt: '2026-06-03T09:35:00Z', note: 'Sofa placed in living room' },
        { id: 'dp_2', url: 'https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?w=600&h=400&fit=crop', uploadedAt: '2026-06-03T09:40:00Z', note: 'Bed assembled in master bedroom' },
      ],
      roomSelection: { roomType: 'living-room', placements: ['Against far wall'], considerations: ['Protect floors'] },
      schedule: { date: '2026-06-03', timeSlot: '8:00 AM - 11:00 AM' },
      contactInfo: { firstName: 'Sarah', lastName: 'Johnson', phone: '(612) 555-0142', email: 'sarah.j@example.com', address: '4521 Lyndale Ave S, Minneapolis, MN 55419', communicationPrefs: ['text', 'email'] },
      additionalDetails: { homeType: 'Single-family home', parking: 'Driveway available', accessNotes: 'Front door, no stairs' },
      orderDetails: { storeName: 'Ashley Furniture', orderNumber: 'AF-8839201', itemDescription: 'Sofa and bed frame' },
      createdAt: '2026-06-01T09:00:00Z',
      assignedCrew: 'Crew A',
      notes: ['Customer prefers morning delivery'],
    },
    {
      id: 'ord_2',
      reference: 'XM-482932',
      status: 'in_transit',
      statusTimeline: [
        { status: 'pending', label: 'Booking Received', timestamp: '2026-06-05T14:00:00Z' },
        { status: 'confirmed', label: 'Confirmed', timestamp: '2026-06-05T15:00:00Z' },
        { status: 'scheduled', label: 'Scheduled', timestamp: '2026-06-06T08:00:00Z', note: 'Crew B assigned' },
        { status: 'dispatched', label: 'Dispatched', timestamp: '2026-06-08T07:30:00Z' },
        { status: 'in_transit', label: 'In Transit', timestamp: '2026-06-08T08:00:00Z' },
      ],
      serviceType: ['delivery', 'removal'],
      items: [
        { id: 'itm_3', category: 'sofa', name: 'Sectional Sofa', quantity: 1, price: 180, action: 'deliver' },
        { id: 'itm_4', category: 'sofa', name: '3-Seat Sofa', quantity: 1, price: 102, action: 'remove' },
      ],
      pricing: { subtotal: 282, discount: 28.2, discountCode: 'ASHLEY15', tax: 21.57, total: 275.37 },
      affiliateCode: 'ASHLEY15',
      photos: [],
      deliveryPhotos: [],
      roomSelection: null,
      schedule: { date: '2026-06-08', timeSlot: '8:00 AM - 11:00 AM' },
      contactInfo: { firstName: 'David', lastName: 'Chen', phone: '(651) 555-0198', email: 'dchen@example.com', address: '8920 Hudson Rd, Woodbury, MN 55125', communicationPrefs: ['text'] },
      additionalDetails: { homeType: 'Townhome', parking: 'Street parking', specialRequests: 'Please haul away old sofa' },
      orderDetails: { storeName: 'Furniture Mart', orderNumber: 'FM-22105', itemDescription: 'New sectional, remove old sofa' },
      createdAt: '2026-06-05T14:00:00Z',
      assignedCrew: 'Crew B',
      notes: [],
    },
    {
      id: 'ord_3',
      reference: 'XM-482933',
      status: 'scheduled',
      statusTimeline: [
        { status: 'pending', label: 'Booking Received', timestamp: '2026-06-07T11:00:00Z' },
        { status: 'confirmed', label: 'Confirmed', timestamp: '2026-06-07T12:00:00Z' },
        { status: 'scheduled', label: 'Scheduled', timestamp: '2026-06-07T12:30:00Z', note: 'Crew A assigned' },
      ],
      serviceType: ['removal'],
      items: [
        { id: 'itm_5', category: 'mattress', name: 'King Mattress', quantity: 2, price: 94, action: 'remove' },
        { id: 'itm_6', category: 'dresser', name: 'Standard Dresser', quantity: 1, price: 81, action: 'remove' },
      ],
      pricing: { subtotal: 175, discount: 0, tax: 14.88, total: 189.88 },
      photos: [],
      deliveryPhotos: [],
      roomSelection: null,
      schedule: { date: '2026-06-10', timeSlot: '1:00 PM - 4:00 PM' },
      contactInfo: { firstName: 'Lisa', lastName: 'Martinez', phone: '(763) 555-0167', email: 'lmartinez@example.com', address: '3210 Fremont Ave N, Minneapolis, MN 55412', communicationPrefs: ['email'] },
      additionalDetails: { homeType: 'Apartment', parking: 'Loading zone', accessNotes: 'Elevator available, 3rd floor' },
      orderDetails: null,
      createdAt: '2026-06-07T11:00:00Z',
      assignedCrew: 'Crew A',
      notes: ['Two mattresses, bring extra straps'],
    },
    {
      id: 'ord_4',
      reference: 'XM-482934',
      status: 'pending',
      statusTimeline: [
        { status: 'pending', label: 'Booking Received', timestamp: '2026-06-08T16:00:00Z' },
      ],
      serviceType: ['delivery'],
      items: [
        { id: 'itm_7', category: 'entertainment_center', name: 'Entertainment Center', quantity: 1, price: 150, action: 'deliver' },
        { id: 'itm_8', category: 'table', name: 'Coffee Table', quantity: 1, price: 60, action: 'deliver' },
      ],
      pricing: { subtotal: 210, discount: 21, discountCode: 'MIKE10', tax: 16.07, total: 205.07 },
      affiliateCode: 'MIKE10',
      photos: [],
      deliveryPhotos: [],
      roomSelection: null,
      schedule: null,
      contactInfo: { firstName: 'Robert', lastName: 'Wilson', phone: '(952) 555-0134', email: 'rwilson@example.com', address: '5601 W 78th St, Edina, MN 55439', communicationPrefs: ['text', 'email'] },
      additionalDetails: { homeType: 'Single-family home', parking: '2-car garage' },
      orderDetails: { storeName: 'Ashley Furniture', orderNumber: 'AF-9901123', itemDescription: 'Entertainment center and coffee table' },
      createdAt: '2026-06-08T16:00:00Z',
      notes: [],
    },
    {
      id: 'ord_5',
      reference: 'XM-482935',
      status: 'completed',
      statusTimeline: [
        { status: 'pending', label: 'Booking Received', timestamp: '2026-05-28T10:00:00Z' },
        { status: 'confirmed', label: 'Confirmed', timestamp: '2026-05-28T11:00:00Z' },
        { status: 'scheduled', label: 'Scheduled', timestamp: '2026-05-29T08:00:00Z' },
        { status: 'dispatched', label: 'Dispatched', timestamp: '2026-05-30T07:30:00Z' },
        { status: 'in_transit', label: 'In Transit', timestamp: '2026-05-30T08:00:00Z' },
        { status: 'delivered', label: 'Delivered', timestamp: '2026-05-30T09:00:00Z' },
        { status: 'completed', label: 'Completed', timestamp: '2026-05-30T10:00:00Z' },
      ],
      serviceType: ['delivery'],
      items: [
        { id: 'itm_9', category: 'bed', name: 'King Bed Frame', quantity: 1, price: 140, action: 'deliver' },
        { id: 'itm_10', category: 'dresser', name: 'Tall Chest', quantity: 1, price: 75, action: 'deliver' },
        { id: 'itm_11', category: 'chair', name: 'Recliner', quantity: 2, price: 85, action: 'deliver' },
      ],
      pricing: { subtotal: 300, discount: 0, tax: 25.5, total: 325.5 },
      photos: [],
      deliveryPhotos: [
        { id: 'dp_3', url: 'https://images.unsplash.com/photo-1617325247661-675ab4b64ae2?w=600&h=400&fit=crop', uploadedAt: '2026-05-30T09:15:00Z' },
        { id: 'dp_4', url: 'https://images.unsplash.com/photo-1595428774223-ef52624120d2?w=600&h=400&fit=crop', uploadedAt: '2026-05-30T09:20:00Z' },
      ],
      roomSelection: { roomType: 'bedroom', placements: ['Bed against window wall'], considerations: ['Remove old packaging'] },
      schedule: { date: '2026-05-30', timeSlot: '8:00 AM - 11:00 AM' },
      contactInfo: { firstName: 'Angela', lastName: 'Thompson', phone: '(612) 555-0189', email: 'athompson@example.com', address: '2200 W Lake St, Minneapolis, MN 55416', communicationPrefs: ['email'] },
      additionalDetails: { homeType: 'Condo', parking: 'Underground garage' },
      orderDetails: { storeName: 'Ashley Furniture', orderNumber: 'AF-7743200', itemDescription: 'Master bedroom set + 2 recliners' },
      createdAt: '2026-05-28T10:00:00Z',
      assignedCrew: 'Crew C',
      notes: [],
    },
  ],
  salespeople: [
    {
      id: 'sp_1',
      name: 'Mike Rodriguez',
      code: 'MIKE10',
      discountPercent: 10,
      totalReferrals: 12,
      totalRevenue: 2840,
      active: true,
    },
    {
      id: 'sp_2',
      name: 'Ashley Johnson',
      code: 'ASHLEY15',
      discountPercent: 15,
      totalReferrals: 8,
      totalRevenue: 1950,
      active: true,
    },
    {
      id: 'sp_3',
      name: 'David Kim',
      code: 'DAVE20',
      discountPercent: 20,
      totalReferrals: 3,
      totalRevenue: 620,
      active: true,
    },
  ],
  crewSlots: [
    { id: 'cs_1', crewName: 'Crew A', date: '2026-06-09', timeSlot: '8:00 AM - 11:00 AM', status: 'available' },
    { id: 'cs_2', crewName: 'Crew A', date: '2026-06-09', timeSlot: '1:00 PM - 4:00 PM', status: 'booked', orderId: 'ord_1' },
    { id: 'cs_3', crewName: 'Crew B', date: '2026-06-09', timeSlot: '8:00 AM - 11:00 AM', status: 'booked', orderId: 'ord_2' },
    { id: 'cs_4', crewName: 'Crew B', date: '2026-06-09', timeSlot: '1:00 PM - 4:00 PM', status: 'available' },
    { id: 'cs_5', crewName: 'Crew C', date: '2026-06-09', timeSlot: '8:00 AM - 11:00 AM', status: 'available' },
    { id: 'cs_6', crewName: 'Crew C', date: '2026-06-09', timeSlot: '1:00 PM - 4:00 PM', status: 'blocked' },
  ],
  notifications: [
    {
      id: 'notif_1',
      userId: 'admin_1',
      type: 'order_status',
      title: 'New Booking',
      message: 'Order XM-482934 received from Robert Wilson',
      read: false,
      createdAt: '2026-06-08T16:05:00Z',
      orderId: 'ord_4',
    },
    {
      id: 'notif_2',
      userId: 'sp_1',
      type: 'order_status',
      title: 'Referral Booked',
      message: 'Your code MIKE10 was used for order XM-482934',
      read: false,
      createdAt: '2026-06-08T16:05:00Z',
      orderId: 'ord_4',
    },
  ],
  users: [
    {
      id: 'admin_1',
      role: 'admin',
      name: 'Admin User',
      email: 'admin@xpressmen.com',
      phone: '(612) 555-0000',
    },
    {
      id: 'sp_1',
      role: 'salesperson',
      name: 'Mike Rodriguez',
      email: 'mike@xpressmen.com',
      phone: '(612) 555-0001',
      code: 'MIKE10',
    },
    {
      id: 'sp_2',
      role: 'salesperson',
      name: 'Ashley Johnson',
      email: 'ashley@xpressmen.com',
      phone: '(612) 555-0002',
      code: 'ASHLEY15',
    },
    {
      id: 'sp_3',
      role: 'salesperson',
      name: 'David Kim',
      email: 'david@xpressmen.com',
      phone: '(612) 555-0003',
      code: 'DAVE20',
    },
  ],
  currentUser: null,
};
