import sgMail from '@sendgrid/mail';
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import pool from '../database.js';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const hasSendGrid = !!process.env.SENDGRID_API_KEY;
if (hasSendGrid) sgMail.setApiKey(process.env.SENDGRID_API_KEY);

const POSTER_PATH = path.join(__dirname, '../public/assets/delivery-complete-poster.jpg');

/**
 * Send proof-of-delivery packet to salesperson when delivery is completed.
 * Includes: branded completion poster + original store order form + delivery photos.
 */
export async function sendProofPacketToSalesperson(orderId) {
  const orderRes = await pool.query(`
    SELECT o.*, u.name as salesperson_name, u.email as salesperson_email
    FROM orders o
    LEFT JOIN users u ON o.salesperson_id = u.id
    WHERE o.id = $1
  `, [orderId]);

  const order = orderRes.rows[0];
  if (!order || !order.salesperson_email) {
    console.log('[ProofPacket] No salesperson email found for order', orderId);
    return { sent: false, reason: 'No salesperson email' };
  }

  // Get original scanned form images
  const formRes = await pool.query('SELECT url FROM order_form_images WHERE order_id = $1', [orderId]);
  const formImages = formRes.rows.map(r => r.url);

  // Get delivery photos
  const photoRes = await pool.query('SELECT url, note FROM delivery_photos WHERE order_id = $1 ORDER BY uploaded_at', [orderId]);
  const deliveryPhotos = photoRes.rows;

  const attachments = [];

  // Attach branded poster if it exists locally
  if (fs.existsSync(POSTER_PATH)) {
    attachments.push({
      filename: 'delivery-complete-xpressmen.jpg',
      content: fs.readFileSync(POSTER_PATH).toString('base64'),
      type: 'image/jpeg',
      disposition: 'attachment',
    });
  }

  const subject = `DELIVERY COMPLETE — Order ${order.reference} — Proof Packet Attached`;

  const html = `
    <div style="font-family:Arial,sans-serif;max-width:600px;margin:0 auto;color:#1a1a1a;">
      <div style="background:#0A1628;padding:24px;text-align:center;">
        <h1 style="color:#E63946;margin:0;font-size:28px;">XMX XPRESSMEN</h1>
        <p style="color:#fff;margin:8px 0 0;font-size:14px;">DELIVERY PROOF PACKET</p>
      </div>

      <div style="padding:24px;background:#fff;border:1px solid #e5e5e5;">
        <h2 style="color:#E63946;margin-top:0;">✅ Delivery Completed</h2>
        <p>Hi ${order.salesperson_name || 'Salesperson'},</p>
        <p>Your order has been successfully delivered. This proof packet contains everything you need for commission processing.</p>

        <div style="background:#f8f9fa;padding:16px;border-radius:8px;margin:16px 0;">
          <p style="margin:4px 0;"><strong>Order:</strong> ${order.reference}</p>
          <p style="margin:4px 0;"><strong>Store Order #:</strong> ${order.order_order_number || 'N/A'}</p>
          <p style="margin:4px 0;"><strong>Customer:</strong> ${order.contact_first_name || ''} ${order.contact_last_name || ''}</p>
          <p style="margin:4px 0;"><strong>Delivered To:</strong> ${order.contact_address || ''}</p>
          <p style="margin:4px 0;"><strong>Total:</strong> $${order.pricing_total?.toFixed(2) || '0.00'}</p>
        </div>

        <h3 style="color:#0A1628;">📎 Attached Files</h3>
        <ul style="line-height:1.8;">
          <li>✅ Xpressmen Delivery Completion Certificate</li>
          ${formImages.length > 0 ? '<li>📄 Original Store Order Form (' + formImages.length + ' image' + (formImages.length > 1 ? 's' : '') + ')</li>' : ''}
          ${deliveryPhotos.length > 0 ? '<li>📷 Delivery Photos (' + deliveryPhotos.length + ' photo' + (deliveryPhotos.length > 1 ? 's' : '') + ')</li>' : ''}
        </ul>

        <p style="margin-top:24px;font-size:12px;color:#666;">
          This email was auto-generated by Xpressmen. If you have questions, contact your admin.
        </p>
      </div>
    </div>
  `;

  const msg = {
    to: order.salesperson_email,
    from: process.env.FROM_EMAIL || 'noreply@xpressmen.com',
    subject,
    html,
    attachments,
  };

  if (hasSendGrid) {
    await sgMail.send(msg);
    console.log('[ProofPacket] Sent to', order.salesperson_email);
  } else {
    console.log('[ProofPacket] MOCK — would send to', order.salesperson_email);
    console.log('[ProofPacket] Subject:', subject);
    console.log('[ProofPacket] Attachments:', attachments.length, 'files +', formImages.length, 'form images +', deliveryPhotos.length, 'delivery photos');
  }

  // Log the event
  await pool.query(`
    INSERT INTO order_messages (id, order_id, sender_name, sender_role, message, created_at)
    VALUES ($1, $2, 'System', 'system', $3, $4)
  `, [
    crypto.randomUUID(),
    orderId,
    `Proof packet sent to ${order.salesperson_name} (${order.salesperson_email}) — ${formImages.length} form images, ${deliveryPhotos.length} delivery photos attached`,
    new Date().toISOString(),
  ]);

  return { sent: true, formImages: formImages.length, deliveryPhotos: deliveryPhotos.length };
}

/**
 * Send proof packet to customer as well (delivery confirmation).
 */
export async function sendDeliveryConfirmationToCustomer(orderId) {
  const orderRes = await pool.query('SELECT * FROM orders WHERE id = $1', [orderId]);
  const order = orderRes.rows[0];
  if (!order?.contact_email) return { sent: false, reason: 'No customer email' };

  const photoRes = await pool.query('SELECT url FROM delivery_photos WHERE order_id = $1 ORDER BY uploaded_at LIMIT 5', [orderId]);
  const photos = photoRes.rows;

  const html = `
    <div style="font-family:Arial,sans-serif;max-width:600px;margin:0 auto;color:#1a1a1a;">
      <div style="background:#0A1628;padding:24px;text-align:center;">
        <h1 style="color:#E63946;margin:0;font-size:28px;">XMX XPRESSMEN</h1>
        <p style="color:#fff;margin:8px 0 0;font-size:14px;">Your delivery is complete!</p>
      </div>
      <div style="padding:24px;background:#fff;border:1px solid #e5e5e5;">
        <h2 style="color:#E63946;">🎉 Delivery Complete</h2>
        <p>Hi ${order.contact_first_name || ''},</p>
        <p>Your order <strong>${order.reference}</strong> has been successfully delivered to:</p>
        <p style="background:#f8f9fa;padding:12px;border-radius:6px;">${order.contact_address || ''}</p>
        ${photos.length > 0 ? `<p>See photos from your delivery below:</p>` : ''}
        <p style="margin-top:24px;font-size:12px;color:#666;">Questions? Reply to this email or call us.</p>
      </div>
    </div>
  `;

  const msg = {
    to: order.contact_email,
    from: process.env.FROM_EMAIL || 'noreply@xpressmen.com',
    subject: `Your Xpressmen Delivery is Complete — ${order.reference}`,
    html,
  };

  if (hasSendGrid) {
    await sgMail.send(msg);
  } else {
    console.log('[ProofPacket] MOCK customer email to', order.contact_email);
  }

  return { sent: true };
}
